---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: shopping-cart-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/instance: minio-credentials
    app.kubernetes.io/component: object-store-credentials
    app.kubernetes.io/part-of: shopping-cart
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: minio-credentials
          app.kubernetes.io/component: object-store-credentials
      data:
        MINIO_ROOT_USER: "{{ index . \"root-user\" }}"
        MINIO_ROOT_PASSWORD: "{{ index . \"root-password\" }}"
  data:
    - secretKey: root-user
      remoteRef:
        key: secret/data/minio/credentials
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: secret/data/minio/credentials
        property: root-password
