---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/instance: keycloak-secrets
    app.kubernetes.io/component: identity-credentials
    app.kubernetes.io/part-of: shopping-cart
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
    template:
      data:
        KEYCLOAK_ADMIN: "admin"
        KC_DB_USERNAME: "keycloak"
  data:
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/keycloak/admin
        property: admin_password
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: secret/data/keycloak/admin
        property: db_password
    - secretKey: LDAP_BIND_CREDENTIAL
      remoteRef:
        key: secret/data/keycloak/admin
        property: ldap_bind_credential
