---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-secrets
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/instance: keycloak-client-secrets
    app.kubernetes.io/component: identity-credentials
    app.kubernetes.io/part-of: shopping-cart
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: external-secret
          app.kubernetes.io/instance: keycloak-client-secrets
          app.kubernetes.io/component: identity-credentials
          app.kubernetes.io/part-of: shopping-cart
  data:
    - secretKey: argocd-client-secret
      remoteRef:
        key: secret/data/keycloak/clients
        property: argocd_client_secret
    - secretKey: order-service-client-secret
      remoteRef:
        key: secret/data/keycloak/clients
        property: order_service_client_secret
    - secretKey: product-catalog-client-secret
      remoteRef:
        key: secret/data/keycloak/clients
        property: product_catalog_client_secret
    - secretKey: grafana-client-secret
      remoteRef:
        key: secret/data/keycloak/clients
        property: grafana_client_secret
